// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGf938PWHAXogHZmhgay9MFnr70Q3pe4',
    appId: '1:73358650827:android:f1278ba855f7b02ee79a4e',
    messagingSenderId: '73358650827',
    projectId: 'regattabuddy',
    databaseURL: 'https://regattabuddy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'regattabuddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3GzKPEl9PD4ezm1DvloNdxWsMtv7-i0',
    appId: '1:73358650827:ios:e8da848108c7fe15e79a4e',
    messagingSenderId: '73358650827',
    projectId: 'regattabuddy',
    databaseURL: 'https://regattabuddy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'regattabuddy.appspot.com',
    iosClientId: '73358650827-50m177n4tc6ri4shah386cq517ei7a7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.regattaBuddy',
  );
}
