name: bumpup-version

on:
  pull_request:
  push:

jobs:
  bumpup-version:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run bumpup-version
        run: |
          version_code=$(grep "versionCode" android/app/build.gradle | awk '{print $2}' | tr -d '\n')
          version_code=$((version_code + 1))
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV
          sed -i "s/versionCode [0-9]\+/versionCode ${{ env.VERSION_CODE }}/g" android/app/build.gradle
#          git config --global user.email "you@example.com"
#          git config --global user.name "Your Name"
#          git commit -am "Bump version code and change version name"
#          git push

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumpup app version